---
issues:
  exclude-dirs:
    - internal/tmp

output:
  unique-by-line: false

linters:
  disable-all: true # implied by presets
  enable:
    # bugs
    - asciicheck
    - bodyclose
    - errcheck
    - errorlint
    # - exhaustive
    - exportloopref
    - gosec
    - govet
    - makezero
    - noctx
    # - scopelint
    # - sqlclosecheck
    - staticcheck
    - typecheck
    # complexity
    - cyclop
    - gocognit
    - gocyclo
    - nakedret
    - nestif
    # format
    - gofmt
    # - gofumpt
    - goimports
    # performance
    # - bodyclose
    # - maligned
    - noctx
    - prealloc
    # - rowserrcheck
    # style
    - asciicheck
    # depguard
    - dogsled
    - dupl
    # - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    # - godox
    # - goerr113
    - goheader
    # - golint # deprecated
    - gomodguard
    - goprintffuncname
    - gosimple
    - importas
    # - interfacer
    - lll
    - makezero
    - misspell
    - mnd
    # - nlreturn
    - nolintlint
    # - paralleltest
    - predeclared
    - revive
    - stylecheck
    - testpackage
    - thelper
    # - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - unused
    - ineffassign
    - unparam
    - unused
  fast: false

linters-settings:
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    # Using %w makes errors part of public API (as they can be inspected). This is not always desired
    errorf: false
  gocyclo:
    min-complexity: 10
  cyclop:
    max-complexity: 10
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/endorama/devid
  nestif:
    min-complexity: 8
  nolintlint:
    allow-unused: true
    require-explanation: true
    require-specific: true
