---
name: Build nightly on push to main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nightly:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install goimports
        run: "go install golang.org/x/tools/cmd/goimports@latest"
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: "task tests"

      - name: Build the CLI
        run: "task build:dev"

      - uses: actions/upload-artifact@v3
        with:
          name: "artifact-${{ matrix.operating-system }}.${{ github.run_id }}.${{ github.run_number }}"
          path: ./devid
