---
name: Build and create release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-release:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'

      - name: Build the CLI
        run: "task build:release"

      - uses: actions/upload-artifact@v3
        with:
          name: "artifact-${{ matrix.operating-system }}.${{ github.run_id }}.${{ github.run_number }}"
          path: |
            ./devid-*
            ./checksum-*
          if-no-files-found: error
          retention-days: 5

  create-release:
    runs-on: ubuntu-latest
    needs: [build-release]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "artifact-macOS-latest.${{ github.run_id }}.${{ github.run_number }}"
      - uses: actions/download-artifact@v3
        with:
          name: "artifact-ubuntu-latest.${{ github.run_id }}.${{ github.run_number }}"
          
      - name: Display structure of downloaded files
        run: ls -R

      - run: touch checksum
      - run: |
          cat checksum-darwin >> checksum
          cat checksum-linux >> checksum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            checksum
            devid-${{github.ref_name}}-darwin-amd64
            devid-${{github.ref_name}}-linux-amd64
