---
name: lint & tests

on:
  pull_request:

jobs:
  lint:
    name: Perform linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/latest
        shell: sh
      - run: devenv ci
      - run: devenv shell task lint

  check:
    name: Check file format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/latest
        shell: sh
      - run: devenv ci
      - run: devenv shell task fmt:check
      - run: devenv shell task go-imports

  tests:
    name: Run tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/latest
        shell: sh
      - run: devenv ci
      - run: devenv shell task tests:coverage
      - uses: codecov/codecov-action@v2
        with:
          verbose: true
