---
name: lint & tests

on:
  pull_request:

jobs:
  lint:
    name: Perform linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1

  tests:
    name: Run tests
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: run tests
        run: "task tests:coverage"

      - uses: codecov/codecov-action@v2
        with:
          verbose: true

