---
name: lint & tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
        with:
          verbose: true

  lint:
    name: Perform linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1

  tests:
    name: Run tests
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'

      - name: run tests
        run: task tests

